#################
#################
# MCD DATA REPO #
#################
#################
from actions import DataConstants


class McdData:
    # Service Info
    def get_service_about_data(self):
        service_about_data = {
            'GTL': {'fullform': '--  Gen. Trade / Storage License  --',
                    'info': 'The Central Licensing & Enforcement Cell (CL&EC), SDMC at deals with the issue and renewal of Municipal General Trade/Storage Licenses under the provisions of Section 417 of DMC Act-1957 (amended Time to Time) and composition of offences u/s 469.\nThe Powers of Commissioner for grant of trade/storage license/permission already stand delegated to Dy. Commissioners/ Addl. Dy.\nCommissioner CL&EC u/s 491 of DMC Act.'
                            '\nSection 417 of the DMC Act-1957 (amended time to time) provides that any person, who desires to establish business of a General Trade and Storage, is required to obtain license from SDMC, particularly for the articles mentioned under Part-I & Part-II of the Eleventh Schedule and other articles notified by the Government Authorities by issuing Public Notices/Orders/Directions from time to time.'
                            '\nThe applicant can apply for the same online through the internet or at any of the CSB center at four zonal offices of SDMC.'
                            '\n Please Redirect to: {} to apply.'.format(DataConstants.gtl_home_page_link)},

            'FTL': {'fullform': '--  Factory License  --',
                    'info': 'Section  416  of  the  MCD  Act,  1957  places  an  obligation  power  to  obtain  prior  permission  of'
                            'Commissioner  MCD  in  writing  on  the  person  desirous  to  establish  in  any  premises  or '
                            'materially  alter,  enlarge  or  extend  any  factory,  workshop  or  trade  premises  in  which  it  is '
                            'intended to employ, steam, electricity, water or other mechanical. '
                            'Once the permission is granted under this Section to install some machinery in a premise, it is '
                            'also an obligatory to obtain a trade license as laid down under Section 417 (i) before starting '
                            'the trade. In order to streamline the smooth and orderly growth of industries as per provisions '
                            'of DMC Act, 1957, the Master Plan of Delhi & Pollution Control Committee, G.N.C.T.D., and '
                            'as  per  directions/judgements  delivered  by  the  Supreme  Court  of  India,  the  provisions  are '
                            'implemented in the NCT of Delhi to minimize the nuisance, health hazard and pollution for '
                            'the orderly industrial growth in the NCT of Delhi. In order to achieve this, certain restrictions '
                            'are imposed in form of licensing conditions for different categories of licenses. \nPlease redirect to : {} to apply'.format(DataConstants.ftl_home_page_link)},
            'VTL': {'fullform': '--  Veterinary License  --',
                    'info': 'Veterinary department deals with wide sphere of work such as Issuance of Licenses of Horse '
                            'Buggies, Dairies, Meat Shops, Meat processing units etc. '
                            'This document covers all the important details of the Veterinary Trade License Application '
                            'like Application features, Interfaces, Functional and Non-Functional requirements, Forms '
                            'and its logical validations.\n Please redirect to : {} to apply'.format(DataConstants.vtl_home_page_link)}
        }
        return service_about_data

    # Trade Categories by Service
    def get_trade_category_by_service(self):
        trade_category_by_service = {
            'GTL': "\n• Conforming industrial area / Flatted group industries and newly Notified 22 areas of industrial area.\n• C.B.D/ sub-C.B.D /Metropolitan city center.\n• Local commercial\n• LSC (Local Shopping Complex).\n• CSC (Commercial Shopping Complex).\n• Community centers.\n• District centers.\n• Service market/ Service center.\n• Pedestrian shopping streets.\n• Commercial areas.\n• Industrial units / plots abutting 24 m row and above in approved layout plan and approved use in sanctions building plan.\n• MLU (mixed land use).\n• Special area category (old city and its extensions).\n• Urban/ Rural villages (only in extended Lal Dora Abadi).\n• Other categories (small shops upto 20 sqm at ground floor in residential area)",
            'VTL': "\n• Cattle Dairy Farm.\n• Meat Shop.\n• Meat Processing Unit.\n• Horse Buggy",
            'FTL': "\n• Conforming (Industrial) Area.\n• DDA/DSIDC/DI Built-up auction/allotted sheds.\n• Industries Outside Industrial Area.\n• Household Category.\n• Local Commercial Category",
            'HTL': "\n• NOT ANY"
        }

        return trade_category_by_service

    def get_document_info_by_service_and_li_update(self):
        document_req_by_service = {'GTL': {
            'NEW': "\n• Proof of legal occupancy of the establishment or allotment letter of govt. agency/tenancy proof/ electricity/water connection bill/landline telephone bill/lease deed /sale deed/GPA.\n• ID proof (with photograph) i.e. Aadhar card/voter id/ pan card/ valid Indian passport/ permanent driving license, bank pass book with photograph and signature.\n• Photograph of the establishment with front-facia, display of goods traded from the premises or the business being carried out from the premises.\n• Site plan/key plan showing the area under the occupation of the applicant or earmarking salient features of the neighbourhood of the site.",
            'RENEWAL': "\n• Self attested scanned copy of original GT/SL.\n• Self attested scanned copy of last receipt of license fee.\n• ID Proof (with photograph) i.e. Aadhar Card/Voter ID/ PAN Card/ Valid Indian Passport/ Permanent driving license.\n• Bank pass book with photograph and signature.",
            'AMENDMENT': "\n• Affidavit by the applicant.\n• Board Resolution/ MOA / Partnership deed.\n• Photograph of site.\n• Lease deed /Rent agreement/layout plan.",
            'SURRENDER': "\n• UID\n• Undertaking\n• Last receipt of payment."},
            'VTL': {'MEAT SHOP': {
                'NEW': "\n• Document  regarding  Age  proof  and  ID  proof)  with photograph i.e. Aadhar Card/ Passport/ Driving License/ Voter ID card/ PAN Card. *In case of non-availability of Age proof, the applicant may submit an undertaking in the form of affidavit regarding his/her age proof.(Mandatory).\n• Proof of legal occupancy of the establishment or allotment letter of Govt.agency / tenancy proof(rent agreement) / latest paid bill of electricity / DJB / Landline phone / Lease deed / Sale deed / GPA.(Mandatory)\n• Blue  Print, Site Plan showing the inside dimension.(Mandatory).\n• Proof  of  water  supply/connection  i.e. current water bill and in case of bore well water testing report.(Mandatory)\n• Medical Fitness certificate issued by authorized registered medical practitioner (MBBS) certifying that the applicant is free form any infectious and contagious disease.(Mandatory).\n• NOC  from  the  Managing  Committee and or Imam of the Masjid if license is applied for shop situated in compound/building of a Masjid (Mosque).\n• Conditional- (If Meat shop exist in Masjid premises)Proof of Electricity supply/connection i.e. current Bill. (For NDMC and EDMC) (Mandatory) *not required for SDMC.\n• Miscellaneous (NM) NDMC.",
                'RENEWAL': "\n• Medical  Fitness  certificate  issued  by  authorized registered medical practitioner (MBBS) certifying that the applicant is free from any infectious and contagious disease.(Mandatory).\n• Residential Address proof (*Conditional-  In  case  of  modification/change in address of applicant).\n• Proof of legal occupancy of the establishment or allotment letter of Govt. agency/tenancy proof/latest paid bill of electricity/DJB/Landline phone/Lease deed/Sale deed/GPA. (*Conditional- in case of modification/ change in occupancy).\n• Proof of water supply/connection i.e. current water bill and in case of bore well water testing report. (Conditional- if source of water changed).\n• Proof which certifies that drainage system changed. (Conditional- if drainage system changed).\n• Copy of Old License (Non Mandatory).\n• Proof of Last paid receipt of Renewal License fee. (Mandatory).\n• Miscellaneous (NM) NDMC.",
                'AMENDMENT': "\n• Owner/Licensee Photo. (Mandatory).\n• Death Certificate of the license holder. Conditional- in case of change of owner.\n• Certificate of the legal heirs of the deceased license holder. Conditional- in case of change of owner.\n• NoC from rest of the legal heirs in the form of affidavit to transfer the license in the name of the one legal heirs. (Conditional- in case of change of owner.).\n• Medical Fitness certificate issued by authorized registered medical practitioner (MBBS) certifying that the applicant is free form any infectious and contagious disease. (Mandatory).\n• Proof of change of constitution. (Conditional).\n• Proof of addition/deletion of partners in case of change in Partnership. (Conditional).\n• Proof of legal occupancy of the establishment or allotment letter of Govt. agency/tenancy proof (rent agreement)/Lease deed/Sale deed/GPA. (Conditional- in case change in Type of Occupancy).\n• Miscellaneous (NM) NDMC.",
                'SURRENDER': "\n• Applicant Identity Proof (Mandatory).\n• Miscellaneous (NM) NDMC"},
                'CATTLE DAIRY FARM': {
                    'NEW': "\n• Certificate from SDM for verification of Rural Area (For Rural Area).\n• Proof of legal occupancy of the establishment or allotment letter of Govt. agency/tenancy proof (rent agreement)/Lease deed/Sale deed/GPA. (Mandatory).\n• Document regarding Age proof and Address proof with photograph i.e. Virtual Aadhar Card/ Passport / Driving License/ Voter ID card. (Mandatory).\n• Blue print, Site Plan and key plan showing the inside dimension i.e. Length, Width & Height of Cattle Shed/Dairy. (Mandatory).\n• Proof of Electricity supply/connection to the cattle shed/ dairy Plot i.e. current Electricity Bill. (Mandatory).\n• Proof of water  supply/connection i.e. current water bill and in case of bore well water testing report. (Mandatory).\n• NOC from the owner of the property to run Dairy Cattle. (Conditional in case of tenancy). (Based).\n• Copy of receipt of latest payment of license fee/ Miltch tax. (Conditional  for  Rural  and  Authorized Dairy).\n• Consent form DPCC to operate Dairy (Non Mandatory).\n• Proof of Temple is registered with Trust/organization. (Conditional- In case of temple).",
                    'RENEWAL': "\n• Address proof (* in case of modification/change in address of applicant). Conditional based.\n• Proof of legal occupancy of the establishment or allotment letter of Govt. agency/tenancy proof (rent agreement)/Lease deed/Sale deed/GPA. (Conditional-  in case of change of ownership).\n• Copy of receipt of latest payment of license fee/ Miltch tax. (Conditional for Authorized Dairy) (Mandatory).\n• Copy of Old License.\n• Copy of receipt of latest payment of license fee/ Miltch tax. (Conditional for Rural and Authorized Dairy).",
                    'AMENDMENT': "\n• Owner/Licensee Photo (Mandatory).\n• Death Certificate of the license holder. Conditional- in case of change of owner.\n• Certificate of the legal heirs of the deceased license holder. Conditional- in case of change of owner.\n• NoC from rest of the legal heirs in the form of affidavit to transfer the license in the name of the one legal heirs. Conditional- in case of change of owner.\n• Proof of change of constitution. (conditional).\n• Proof of addition/deletion of partners n case of change in Partnership. Conditional- in case of change in details of partners.\n• Proof of legal occupancy of the establishment or allotment letter of Govt. agency/tenancy proof (rent agreement)/Lease deed/Sale deed/GPA. (Conditional).",
                    'SURRENDER': "\n• Applicant Identity Proof."},
                'MEAT PROCESSING UNIT': {
                    'NEW': "\n• Valid copy of Factory License (Mandatory) VTL-016 – Common for all three corporation.\n• Valid copy of Health Trade License (Mandatory) (SDMC).\n• Document regarding Age proof and ID proof) with photograph i.e. Aadhar Card/Passport/Driving License/Voter ID card/PAN Card/ any other proof issued by the Govt. Body.(M) Common for all three corporation.\n• Proof of ownership/ occupancy of the establishment or allotment letter of Govt. agency/tenancy proof (rent agreement)/Lease deed/Sale deed/GPA. (M) (SDMC).\n• Blue  print, Site Plan and key plan showing the inside dimension i.e. Length, Width & Height of establishment. (M) Common for all three corporation.\n• Proof of water supply/connection i.e. current water bill and in case of bore well water testing report. (M) Common for all three corporation.\n• Miscellaneous (NDMC)\n• Medical Fitness certificate issued by authorized registered medical practitioner (MBBS) certifying that the applicant and meat handler are free form any infectious and contagious disease. (M) (VTL031) (MPU) (NDMC).\n• Old copy of license (NM) Common for all three corporation.\n• last paid renewal fee receipt (M) Common for all three corporation.\n• Proof of water supply/connection i.e. current water bill/ bore-well water testing report in case of modification/change in water supply. (NM)- Conditional (Common for all three corporation).\n• Proof which certifies that drainage system changed. (NM)- Conditional (Common for all three corporation).",
                    'AMENDMENT': "\n• Medical Fitness certificate issued by authorized registered medical practitioner (MBBS) certifying that the applicant and meat handler are free form any infectious and contagious disease. (M) (VTL031) (MPU) (NDMC).\n• Miscellaneous (NDMC).\n• Owner/Licensee Photo (Mandatory) Common for all three corporation.\n• Death Certificate of the license holder (Non mandatory) Conditional- Common for all three corporation.\n• Certificate of the legal heirs of the deceased license holder (mandatory) Conditional- Common for all three corporation.\n• NOC FROM REST OF THE LEGAL HEIRS IN THE FORM OF AFFIDAVIT TO TRANSFER THE LICENSE IN THE NAME OF THE ONE LEGAL HEIRS. (Mandatory) Conditional- Common for all three corporation.\n• Proof of change of constitution (conditional).- Common for all three corporation.\n• Proof of addition/deletion of partners in case of change in Partnership (conditional) Common for all three corporation.",
                    'SURRENDER': "\n• Applicant ID Proof (SDMC/NDMC/EDMC.\n• Miscellaneous (NDMC)"},
                'HORSE BUGGY': {'NEW': "\n• Photograph of horse buggy with horse/mare. (M) - VTL026.\n• DOB proof of owner like Birth Certificate,10th Certificate Aadhar Card/Passport/Driving License/Voter ID card. In case of non-availability of Age proof, the applicant may submit an undertaking in the form of affidavit regarding his/her age proof. (M) - VTL027.\n• Document regarding Address proof. (M) - VTL028.\n• Veterinary Heath certificate w.r.t Horse/mare issued by registered  Veterinary Doctor in (Delhi). (M)- VTL029.\n• Miscellaneous (NDMC).",
                                'RENEWAL': "\n• Address proof (* in case of modification/change in address of applicant). Conditional based.\n• Photograph of horse buggy with horse/mare. (M).\n• Vetrinary Heath certificate w.r.t Horse/mare issued by registered Veterinary Doctor in Delhi). (M).\n• Miscellaneous (NDMC).\n• Last paid Renewal License Fee Receipt (Mandatory).",
                                'AMENDMENT': "\n• Owner/Licensee Photo (M).\n• Death Certificate of the license holder (NM) Conditional.\n• Certificate of the legal heirs of the deceased license holder (NM) Conditional (VTL-013).\n• NOC FROM REST OF THE LEGAL HEIRS IN THE FORM OF AFFIDAVIT TO TRANSFER THE LICENSE IN THE NAME OF THE ONE LEGAL HEIRS. (Conditional) (VTL-014).\n• Proof of change of constitution (conditional).\n• Proof of addition/deletion of partners in case of change in Partnership- Conditional.\n• Miscellaneous (NDMC)",
                                'SURRENDER': "\n• Applicant ID Proof (SDMC/NDMC/EDMC).\n• Miscellaneous (NDMC)."},
            },
            'FTL': {'NEW': {
                'CONFORMING INDUSTRIAL AREA': "\n• Ownership/registered occupancy proof in shape of perpetual deed, lease deed alongwith NOC of owner (complete chain of ownership not required).\n• Company details i.e., certificate of incorporation/MOU, authority letter in name of applicant/NOC of partner with partnership deed.\n• Building plan or sanction letters i.e. Form C & D.\n• Self-undertaking/Self declaration on letter head (No affidavit required).\n• Additional/Optional documents, if any.\n• DPCC consent.\n• Fire NOC (If premises come under purview above 250 sqm).",
                'DDA/DSIDC/DI BUILT-UP AUCTION/ALOTTED SHEDS': "\n• Ownership/registered occupancy proof in shape of perpetual deed, lease deed alongwith NOC of owner (complete chain of ownership not required).\n• Company details i.e., certificate of incorporation/MOU, authority letter in name of applicant/NOC of partner with partnership deed.\n• Building plan or sanction letters i.e.  Form C & D.\n• Self-undertaking/Self declaration on letter head (No affidavit required).\n• Additional/Optional documents, if any.\n• DPCC consent.\n• Fire NOC (If premises come under purview above 250 sqm).",
                'INDUSTRIES OUTSIDE INDUSTRIAL AREA': "\n• Ownership/registered occupancy proof in shape of perpetual deed, lease deed alongwith NOC of owner (complete chain of ownership not required).\n• Company details i.e., certificate of incorporation/MOU, authority letter in name of applicant/NOC of partner with partnership deed.\n• Self-undertaking /Self declaration on letter head (No affidavit required).\n• Key plan/Site plan.\n• Additional/Optional documents, if any.\n• DPCC consent.\n• Fire NOC (If premises come under purview above 250 sqm).",
                'HOUSEHOLD CATEGORY': "\n• Ownership/registered occupancy proof /lease deed alongwith NOC of owner.\n• Details applicant i.e. Photo ID proof.\n• Copy of electricity bill & Site plan/key plan.\n• Self-undertaking /Self declaration on letter head (No affidavit required).\n• Additional/Optional documents, if any.\n• DPCC consent. (Not required being A category non-polluting trade).",
                'LOCAL COMMERCIAL CATEGORY': "\n• Ownership/registered occupancy proof /lease deed alongwith NOC of owner.\n• Copy of electricity bill.\n• Sanctioned building plan & site plan/key plan.\n• Self-undertaking /Self-declaration on letter head (No affidavit required).\n• DPCC consent.\n• Certificate of safety of explosives.\n• Fire NOC (If premises come under purview above 250 sqm)."
            },
                'RENEWAL': "\n• DPCC.\n• Fire NOC (If area greater than 250 Sq. Mt).",
                'AMENDMENT': "\n• Constitution of firm/Incorporation certificate in case of public or private limited company. (for Change of constitution of firm).\n• NOC/Authority in favor of applicant (for change of name of director/partner).\n• Details of proposed machinery with H.P. rating. (For change in power load).\n• Undertaking on company letter head.\n• Additional Undertaking/indemnity Bond/affidavit as prescribed for clusters of industrial concentration earmarked for redevelopment into conforming industrial areas as per MPD-2021.",
                'SURRENDER': "\n• UID.\n• 'Undertaking'"
            }

        }

        return document_req_by_service

    def get_steps_to_apply(self):
        steps_to_apply_by_service = {
            "GTL": '• Step 1 : First redirect to {}'.format(DataConstants.gtl_home_page_link)+'\n• Step 2 : If you have registered yourself before, enter the registered mobile number in the first text field.\n• Step 3 : Click on Generate OTP, on receiving OTP enter it in the second text field and click on Login Button.\n• Step 4 : Once redirected to Service Homepage, click on first option (General Trade License).\n• Step 5 : Now click on "APPLY NEW GT LICENSE".\n• Step 6 : Fill the all required fields and click on submit.\n• Step 7 : Confirm the Payment Invoice and click on "PAY ONLINE".\n• Step 8 : Complete the Payment and Done!',
            "FTL": '• Step 1 : First Redirect to {}'.format(DataConstants.ftl_home_page_link)+'\n• Step 2 : If you have Registered yourself before, enter the registered mobile number in the first text field.\n• Step 3 : Click on Generate OTP, on receiving OTP enter it into the second text field and click on Login button.\n• Step 4 : Now click on "APPLY NEW FACTORY LICENSE" button.\n• Step 5 : Fill the all required fields and click on submit.\n• Step 6 : Confirm the Payment Invoice and click on "PAY ONLINE".\n• Step 7 : Complete the Payment and Done!',
            "VTL": '• Step 1 : First Redirect to {}'.format(DataConstants.vtl_home_page_link)+'\n• Step 2 : If you have Registered yourself before, enter the registered mobile number in the first text field.\n• Step 3 : Click on Generate OTP, on receiving OTP enter it into the second text field and click on Login button.\n• Step 4 : Once redirected to Service Homepage, click on "Apply New VT License" in the drawer located on the left.\n• Step 5 : Fill the all required fields and click on submit.\n• Step 6 : Confirm the Payment Invoice and click on "PAY ONLINE".\n• Step 7 : Complete the Payment and Done!'
        }
        return steps_to_apply_by_service
